import {
    faAngleLeft,
    faArrowsAltH,
    faBriefcase,
    faChevronDown,
    faChevronUp,
    faCog,
    faExclamationCircle,
    faEye,
    faEyeSlash,
    faMapMarkerAlt,
    faMoneyBillWave,
    faPhoneAlt,
    faPlusCircle,
    faSearch,
    faTimes,
    faTrash,
    faUser,
    faUserCircle,
    faHouseUser,
    faHome,
    faTachometerAlt,
    faGamepad,
    faStethoscope,
    faQuestion,
    faHospitalSymbol,
} from '@fortawesome/free-solid-svg-icons';

export const GLOBAL_ICONS = {
    angleLeft: faAngleLeft,
    mapMarkerAlt: faMapMarkerAlt,
    phoneAlt: faPhoneAlt,
    eye: faEye,
    eyeSlash: faEyeSlash,
    times: faTimes,
    chevronUp: faChevronUp,
    chevronDown: faChevronDown,
    search: faSearch,
    exclamationCircle: faExclamationCircle,
    briefcase: faBriefcase,
    user: faUser,
    cog: faCog,
    plusCircle: faPlusCircle,
    trash: faTrash,
    moneyBillWave: faMoneyBillWave,
    arrowsAltH: faArrowsAltH,
    userCircle: faUserCircle,
    houseUser: faHouseUser,
    home: faHome,
    telemetry: faTachometerAlt,
    gamepad: faGamepad,
    stethoscope:faStethoscope,
    question: faQuestion,
    help : faHospitalSymbol
};
